### PR TITLE
Linting updates

### PR DESCRIPTION
**Pull request by ben16williams**
## Brief Description

Update linter linting rules to be more robust and resolve all linting errors.  There should be no functional changes in this PR. Also updated some packages in `client/package.json`. There are still a large number of warnings produced by the linter in the client and server which need to be resolved, but the client now builds without errors which is needed for deployment. 

In order to remove all errors, some rules that should be in place are ignored in the linter config file. These being `@typescript-eslint/no-unused-vars`, `@typescript-eslint/ban-ts-comment`, and `react/no-unknown-property`. A ticket has been created to remove these and resolve the underlying causes of the errors. 

`client/src/components/Ticketing/ticketingmanager/Events/events_pages/eventsSlice.spec.ts` will also need to be looked at as its current state was causing many errors. This is a unit test file and has no functional implications. 

## References Issue

none

## Type of change

- [x] Bug fix
- [ ] Feature
- [ ] Major change (potentially breaking, list anything that is broken below)
- [x] Documentation

### Breaking Changes

Linter throws warnings 

## Testing done

Describe tests that were used, along with instructions for testing.
Ran unit tests

...

- [x] Docker was used.
- [ ] Docker was not used and I have listed my configuration below.

**System Specifications**:
* Operating System: windows 10
* Node Version: 16.18.0
* NPM Version: 8.19.3

## Checklist:

- [x] My code follows the styling guidelines.
- [] I have added unit tests and verified that they pass.
- [x] I have used the linter and fixed any linting issues.
- [x] I have commented the code.
- [x] I have adjusted the documentation to match the changed code.
- [x] Prior to submitting the PR, I made sure the latest changes were merged with my branch.
- [x] Existing tests pass locally with changes.

### CODE REVIEW

**Comment by ben16williams** [comment]
Since some packages are updated/added in this PR, whoever reviews it will need to delete there local docker images before composing up

**Comment by arasmu2** [comment]
OK I deleted my docker images and rebuilt. They build successfully and the site works. That being said:

- There are still some dependency errors in the `npm install` actions for the client and server. They all appear to resolve themselves though, so idk if this is a real issue.
-There are still linting errors being shown, most of which appear to be  of the `@typescript-eslint` or `jsdoc` variety. Is this supposed to fully eliminate these errors, or just set the stage for future work that will resolve them?

**Comment by ben16williams** [comment]
> OK I deleted my docker images and rebuilt. They build successfully and the site works. That being said:
> 
> * There are still some dependency errors in the `npm install` actions for the client and server. They all appear to resolve themselves though, so idk if this is a real issue.

These I would still expect and the current fix is still to use the force flag when installing the dependencies in the docker file. This should still be ok for now though because the purpose of this pr is to get the client/server to build without errors

> * There are still linting errors being shown in the command line, most of which appear to be  of the `@typescript-eslint` or `jsdoc` variety. Is this supposed to fully eliminate these errors, or just set the stage for future work that will resolve them?

Are they linting errors or warnings? For me, there was a large number of warnings remaining (some introduced with the updates to the linting config) but no errors. Any errors should also get overplayed when you first bring up the client in the browser, or at least they are for me

**Comment by arasmu2** [comment]
They don't overlay in the browser for me so I'm going to assume that means they're warnings, not errors.

**Review by arasmu2 — APPROVED** [review]

**Pull request merged**
