### PR TITLE
NavBar goes away when click outside

### PR DESCRIPTION
**Pull request by RuskiDre1**
### Description
added useRef to close navbar without rerender
### Risks
none really
### Validation
tested locally
### Issue
*Link to corresponding issue*
https://github.com/WonderTix/WonderTix/issues/243
### Operating System
Mac M1 Pro

### CODE REVIEW

**Review by henrykaus — CHANGES_REQUESTED** [review]
This solution works great and appears to function perfectly! It looks like there are actually three of these nav bars across the application though (ideally, there should really only be one, we'll consolidate in the future): this one on the main page, the one for the ticketing admin pages (`Ticketing/ticketingmanager/udash_navbar.tsx`) and one for the CRM admin pages (`CRM/Navigation.tsx`). These other two navbars could use this functionality as well

**Comment by RuskiDre1** [comment]
> This solution works great and appears to function perfectly! It looks like there are actually three of these nav bars across the application though (ideally, there should really only be one, we'll consolidate in the future): this one on the main page, the one for the ticketing admin pages (`Ticketing/ticketingmanager/udash_navbar.tsx`) and one for the CRM admin pages (`CRM/Navigation.tsx`). These other two navbars could use this functionality as well

Ohhh that explains it haha, I was trying to get it to work across all pages but if there's several navs that makes sense. Should I spring a new ticket to combine all the navs in a single component ? I'll add the changes to the other 2 in the mean time.

**Comment by henrykaus** [comment]
> > This solution works great and appears to function perfectly! It looks like there are actually three of these nav bars across the application though (ideally, there should really only be one, we'll consolidate in the future): this one on the main page, the one for the ticketing admin pages (`Ticketing/ticketingmanager/udash_navbar.tsx`) and one for the CRM admin pages (`CRM/Navigation.tsx`). These other two navbars could use this functionality as well
> 
> Ohhh that explains it haha, I was trying to get it to work across all pages but if there's several navs that makes sense. Should I spring a new ticket to combine all the navs in a single component ? I'll add the changes to the other 2 in the mean time.

Yep, that would be perfect. Thanks!

**Review by henrykaus — APPROVED** [review]
Everything works great! Thanks for adapting the other two dropdown menus! Feel free to merge at your discretion

**Pull request merged**
