### PR TITLE
Router testing setup

### PR DESCRIPTION
**Pull request by arasmu2**
## Brief Description

Added router testing for the following routers: accounts, contacts, donations, doorlist

Tests use Jest / Supertest to mock the service functions and provide the appropriate status code to the router

Required NPM installs:
npm install --save-dev supertest 
npm install --save @types/supertest
npm install --save-dev jest
npm install --save @types/jest

## References Issue

Issue #

## Type of change

- [ ] Bug fix
- [x] Feature
- [ ] Major change (potentially breaking, list anything that is broken below)
- [ ] Documentation

### Breaking Changes

None

## Testing done

- [x] Docker was not used and I have listed my configuration below.

**System Specifications**:
* Operating System: Windows 10
* Node Version: 16.16.0
* NPM Version: 8.11.0

## Checklist:

- [x] My code follows the styling guidelines.
- [x] I have added unit tests and verified that they pass.
- [x] I have used the linter and fixed any linting issues.
- [x] I have commented the code.
- [x] I have adjusted the documentation to match the changed code.
- [x] Prior to submitting the PR, I made sure the latest changes were merged with my branch.
- [x] Existing tests pass locally with changes.

### CODE REVIEW

**Comment by PDXChristian** [comment]
Is this ready to be merged, or is it still in progress? It looks like some of the tests are commented out.

**Comment by arasmu2** [comment]
> Is this ready to be merged, or is it still in progress? It looks like some of the tests are commented out.

The tests that are commented out are for **_doorlist.router_**, which currently doesn’t return any status codes, so there’s nothing really to test yet. My assumption is that this is because _**_doorlist.router_**_ is currently unfinished/incomplete, so I just put the outline of a test in there for the future. If you would prefer those tests be removed for now I can do that.

**Comment by PDXChristian** [comment]
> My assumption is that this is because doorlist.router is currently unfinished/incomplete, so I just put the outline of a test in there for the future.

Ahh nope. That's perfect. There are some routes that previously didn't return anything. We have made some changes to them, but will not be merging them into development until later today. Thanks for your hard work on finishing up these unit tests!

**Review by ben16williams — APPROVED** [review]
LGTM

**Comment by arasmu2** [comment]
Sorry guys I goofed. I got an email that Ben approved this PR and assumed that he merged it as well. I pushed another test suite for **_task_notes.router_** and it reset/blocked the PR. If I could get another approval I'll make sure to merge it this time.

**Review by ben16williams — APPROVED** [review]

**Pull request merged**
