### PR TITLE
[WT 480] Added Showing detail to Admin and Patron UI

### PR DESCRIPTION
**Pull request by benfaustin95**
### Description
Added the ability to add to/edit the description of each showing. The description is then displayed to the patron when selecting a showing.

Also updated the button styling to be consistent across the Event page. 

image
image
image
image

*In the WonderTix minimum doc it was referred to as detail so that is what I referred to it as in the UI but that can easily be updated to something else. 

### Risks
Might have missed an area where to description needs to be displayed.

### Validation
Manually tested adding/editing the description. 

### Issue
#480 

### Operating System
M1 Mac

### CODE REVIEW

**Review by ben16williams — DISMISSED** [review]
lgtm💯

**Comment by ben16williams** [comment]
> Might have missed an area where to description needs to be displayed.

I could see PPH wanting the description to be displayed with the item in the cart, but I'm ok with just following up on that for now

**Comment by benfaustin95** [comment]
> > Might have missed an area where to description needs to be displayed.
> 
> I could see PPH wanting the description to be displayed with the item in the cart, but I'm ok with just following up on that for now

I added the description to the cart.

**Comment by ben16williams** [comment]
> I added the description to the cart items.

Looks great, thanks for doing that! Henry just merged it so it didn't occur to me until now... but we probably will want to also include the description with the `orderitems` in the contact orders page

**Comment by benfaustin95** [comment]
> > I added the description to the cart items.
> 
> Looks great, thanks for doing that! Henry just merged it so it didn't occur to me until now... but we probably will want to also include the description with the `orderitems` in the contact orders page

Updated

**Review by ben16williams — APPROVED** [review]
lgtm. thanks for iterating

**Review by henrykaus — APPROVED** [review]

**Pull request merged**
