### PR TITLE
Donor management

### PR DESCRIPTION
**Pull request by lee-112**
# Donor-Management PR #1

## Updated auth.js

Updated link for issuerBaseURL

### CODE REVIEW

**Review by xiivi — APPROVED** [review]
Approved.

**Comment by xiivi** [comment]
Approve pr

**Comment by ben16williams** [comment]
Hello @lee-112 and @xiivi, can we please revert this PR? This adds a superfluous `.DS_Store` file at the root level of the project which is generated when viewing files on a mac with the finder app iirc, and the unresolved git conflict block in `auth.js` causes the tests to fail for everybody. I'm not sure how this was merged actually since the failing github actions should have prevented that?

**Comment by ben16williams** [comment]
I created a PR to revert this, can one of you please review it when you have a chance? [https://github.com/WonderTix/WonderTix/pull/287](https://github.com/WonderTix/WonderTix/pull/287)

**Comment by lee-112** [comment]
Sorry about that. Our group was doing a test run for committing PR.

**Comment by ben16williams** [comment]
No worries! It's a good opportunity to make sure that the branch protections are working

**Pull request merged**
